### ISSUE TITLE
Implement optional in all repositories

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#204]
As a **user**, I want to use `Optional` in all find by something methods defined in `repostitory` package **so that** I can use the new [JPA convention](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html)

**Acceptance Criteria**
- All repositories are using `Optional` as a return type in find by methods
- All test cases are passing

**Comment by marki2121** [comment]
Can you assignee this to me?

**Comment by josdem** [comment]
Hi @marki2121 I assigned the issue to you, I appreciate your collaboration! Happy to answer any questions you might have.

**Comment by marki2121** [comment]
Hi i am getting an error about not heaving google credentials. So all i wanted to ask is if i can create a PR so you can ran the tests when i am done.

  Error creating bean with name 'googleStorageWriter': Invocation of init method failed; nested exception is java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

**Comment by josdem** [comment]
> Hi i am getting an error about not heaving google credentials. So all i wanted to ask is if i can create a PR so you can ran the tests when i am done.
> 
> Error creating bean with name 'googleStorageWriter': Invocation of init method failed; nested exception is java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

Hi @marki2121, thanks for the feedback! The error was due to the missing credentials; however, I ran the test for you, and all good. Thanks for your contribution!
